image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/nodejs-ci-test
  tag: d15c007035b1e953c1c59682848bf44396e4f7e1
  pullPolicy: IfNotPresent

replicaCount: 3

containerPort: 3000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

livenessProbe:
  enabled: true
  httpGet:
    path: /health

readinessProbe:
  enabled: true
  httpGet:
    path: /health

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits: {}
