image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/payment-api
  tag: 'f992b047955da7ef92efb0f75393c04d0fc3e5a4'
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
