image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/payment-api
  tag: 'b8df988c1f6cdc41b207a979c2394c14114e389a'
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
