image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/nodejs-ci-test
  tag: 8d7159aa2db43d7920b8df2584c757d5e283f998
  pullPolicy: IfNotPresent
replicaCount: 2
containerPort: 3000
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
livenessProbe:
  enabled: true
  httpGet:
    path: /health
readinessProbe:
  enabled: true
  httpGet:
    path: /health
resources:
  requests:
    cpu: 100m
    memory: 128Mi
