image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/python-ci-test
  tag: '283eea0548e178e3376136eee6837befe8713ea5'
  pullPolicy: IfNotPresent
replicaCount: 1
containerPort: 8000
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
