image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/nodejs-secret-golden-path-test
  tag: 'a9889cb1bb6018207f11ebafd91e2e45e5869f4b'
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
