image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/billing-api
  tag: '41b270ab50272872e7ddd02465512ce0bfe4dc1c'
  pullPolicy: IfNotPresent
replicaCount: 1
containerPort: 8000
service:
  targetPort: 8000
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
