image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/pipeline-end-end-test
  tag: '170cf487346cd9288f66bd44f6a28c6fc2575df1'
  pullPolicy: IfNotPresent
replicaCount: 2
containerPort: 3000
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
livenessProbe:
  enabled: true
  httpGet:
    path: /health
readinessProbe:
  enabled: true
  httpGet:
    path: /health
resources:
  requests:
    cpu: 100m
    memory: 128Mi
