image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/pipeline-end-end-test
  tag: '5efba7efb90dd0b2a29e00598a7e3f6447621240'
  pullPolicy: IfNotPresent
replicaCount: 2
containerPort: 3000
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
livenessProbe:
  enabled: true
  httpGet:
    path: /health
readinessProbe:
  enabled: true
  httpGet:
    path: /health
resources:
  requests:
    cpu: 100m
    memory: 128Mi
