image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/authentication-api
  tag: 'a175017389ecb338216466d1484e38b9868f64b2'
  pullPolicy: IfNotPresent
replicaCount: 1
containerPort: 8080
service:
  targetPort: 8080
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
