image:
  repository: 980829302319.dkr.ecr.eu-west-2.amazonaws.com/platform-pipeline-test
  tag: '1bfd57b84ccbc6267fac7ae3dd85802e4b60ef3d'
  pullPolicy: IfNotPresent

replicaCount: 2

containerPort: 3000

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

livenessProbe:
  enabled: true
  httpGet:
    path: /health

readinessProbe:
  enabled: true
  httpGet:
    path: /health

resources:
  requests:
    cpu: 100m
    memory: 128Mi
